// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.6
// source: asr.proto

package asr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 处理视频请求
type ProcessVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    uint64                 `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,2,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	VideoPath     string                 `protobuf:"bytes,3,opt,name=video_path,json=videoPath,proto3" json:"video_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessVideoRequest) Reset() {
	*x = ProcessVideoRequest{}
	mi := &file_asr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessVideoRequest) ProtoMessage() {}

func (x *ProcessVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessVideoRequest.ProtoReflect.Descriptor instead.
func (*ProcessVideoRequest) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessVideoRequest) GetMaterialId() uint64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *ProcessVideoRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *ProcessVideoRequest) GetVideoPath() string {
	if x != nil {
		return x.VideoPath
	}
	return ""
}

// 处理视频响应
type ProcessVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Segments      []*ASRSegment          `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessVideoResponse) Reset() {
	*x = ProcessVideoResponse{}
	mi := &file_asr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessVideoResponse) ProtoMessage() {}

func (x *ProcessVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessVideoResponse.ProtoReflect.Descriptor instead.
func (*ProcessVideoResponse) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessVideoResponse) GetSegments() []*ASRSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

// 获取分段请求
type GetSegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    uint64                 `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentsRequest) Reset() {
	*x = GetSegmentsRequest{}
	mi := &file_asr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentsRequest) ProtoMessage() {}

func (x *GetSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentsRequest.ProtoReflect.Descriptor instead.
func (*GetSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{2}
}

func (x *GetSegmentsRequest) GetMaterialId() uint64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

// 获取分段响应
type GetSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Segments      []*ASRSegment          `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentsResponse) Reset() {
	*x = GetSegmentsResponse{}
	mi := &file_asr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentsResponse) ProtoMessage() {}

func (x *GetSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentsResponse.ProtoReflect.Descriptor instead.
func (*GetSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{3}
}

func (x *GetSegmentsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSegmentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSegmentsResponse) GetSegments() []*ASRSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

// 搜索分段请求
type SearchSegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MaterialId    uint64                 `protobuf:"varint,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"` // 可选，指定材料ID
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                             // 可选，结果数量限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSegmentsRequest) Reset() {
	*x = SearchSegmentsRequest{}
	mi := &file_asr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSegmentsRequest) ProtoMessage() {}

func (x *SearchSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSegmentsRequest.ProtoReflect.Descriptor instead.
func (*SearchSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{4}
}

func (x *SearchSegmentsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSegmentsRequest) GetMaterialId() uint64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *SearchSegmentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 搜索分段响应
type SearchSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Segments      []*ASRSegment          `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSegmentsResponse) Reset() {
	*x = SearchSegmentsResponse{}
	mi := &file_asr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSegmentsResponse) ProtoMessage() {}

func (x *SearchSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSegmentsResponse.ProtoReflect.Descriptor instead.
func (*SearchSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{5}
}

func (x *SearchSegmentsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchSegmentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchSegmentsResponse) GetSegments() []*ASRSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

// 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_asr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{6}
}

// 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_asr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ASR分段信息
type ASRSegment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MaterialId      uint64                 `protobuf:"varint,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	StartTime       float32                `protobuf:"fixed32,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         float32                `protobuf:"fixed32,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Text            string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Confidence      float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	EmbeddingVector string                 `protobuf:"bytes,7,opt,name=embedding_vector,json=embeddingVector,proto3" json:"embedding_vector,omitempty"` // JSON格式的向量数据
	CreatedAt       string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ASRSegment) Reset() {
	*x = ASRSegment{}
	mi := &file_asr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASRSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASRSegment) ProtoMessage() {}

func (x *ASRSegment) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASRSegment.ProtoReflect.Descriptor instead.
func (*ASRSegment) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{8}
}

func (x *ASRSegment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ASRSegment) GetMaterialId() uint64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *ASRSegment) GetStartTime() float32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ASRSegment) GetEndTime() float32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ASRSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ASRSegment) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ASRSegment) GetEmbeddingVector() string {
	if x != nil {
		return x.EmbeddingVector
	}
	return ""
}

func (x *ASRSegment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ASRSegment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_asr_proto protoreflect.FileDescriptor

const file_asr_proto_rawDesc = "" +
	"\n" +
	"\tasr.proto\x12\x03asr\"r\n" +
	"\x13ProcessVideoRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\x04R\n" +
	"materialId\x12\x1b\n" +
	"\tvideo_url\x18\x02 \x01(\tR\bvideoUrl\x12\x1d\n" +
	"\n" +
	"video_path\x18\x03 \x01(\tR\tvideoPath\"w\n" +
	"\x14ProcessVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\bsegments\x18\x03 \x03(\v2\x0f.asr.ASRSegmentR\bsegments\"5\n" +
	"\x12GetSegmentsRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\x04R\n" +
	"materialId\"v\n" +
	"\x13GetSegmentsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\bsegments\x18\x03 \x03(\v2\x0f.asr.ASRSegmentR\bsegments\"d\n" +
	"\x15SearchSegmentsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vmaterial_id\x18\x02 \x01(\x04R\n" +
	"materialId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"y\n" +
	"\x16SearchSegmentsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\bsegments\x18\x03 \x03(\v2\x0f.asr.ASRSegmentR\bsegments\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x94\x02\n" +
	"\n" +
	"ASRSegment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vmaterial_id\x18\x02 \x01(\x04R\n" +
	"materialId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x02R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x02R\aendTime\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\x12)\n" +
	"\x10embedding_vector\x18\a \x01(\tR\x0fembeddingVector\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt2\xa0\x02\n" +
	"\n" +
	"ASRService\x12C\n" +
	"\fProcessVideo\x12\x18.asr.ProcessVideoRequest\x1a\x19.asr.ProcessVideoResponse\x12@\n" +
	"\vGetSegments\x12\x17.asr.GetSegmentsRequest\x1a\x18.asr.GetSegmentsResponse\x12I\n" +
	"\x0eSearchSegments\x12\x1a.asr.SearchSegmentsRequest\x1a\x1b.asr.SearchSegmentsResponse\x12@\n" +
	"\vHealthCheck\x12\x17.asr.HealthCheckRequest\x1a\x18.asr.HealthCheckResponseB)Z'github.com/RigelNana/arkstudy/proto/asrb\x06proto3"

var (
	file_asr_proto_rawDescOnce sync.Once
	file_asr_proto_rawDescData []byte
)

func file_asr_proto_rawDescGZIP() []byte {
	file_asr_proto_rawDescOnce.Do(func() {
		file_asr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)))
	})
	return file_asr_proto_rawDescData
}

var file_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_asr_proto_goTypes = []any{
	(*ProcessVideoRequest)(nil),    // 0: asr.ProcessVideoRequest
	(*ProcessVideoResponse)(nil),   // 1: asr.ProcessVideoResponse
	(*GetSegmentsRequest)(nil),     // 2: asr.GetSegmentsRequest
	(*GetSegmentsResponse)(nil),    // 3: asr.GetSegmentsResponse
	(*SearchSegmentsRequest)(nil),  // 4: asr.SearchSegmentsRequest
	(*SearchSegmentsResponse)(nil), // 5: asr.SearchSegmentsResponse
	(*HealthCheckRequest)(nil),     // 6: asr.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 7: asr.HealthCheckResponse
	(*ASRSegment)(nil),             // 8: asr.ASRSegment
}
var file_asr_proto_depIdxs = []int32{
	8, // 0: asr.ProcessVideoResponse.segments:type_name -> asr.ASRSegment
	8, // 1: asr.GetSegmentsResponse.segments:type_name -> asr.ASRSegment
	8, // 2: asr.SearchSegmentsResponse.segments:type_name -> asr.ASRSegment
	0, // 3: asr.ASRService.ProcessVideo:input_type -> asr.ProcessVideoRequest
	2, // 4: asr.ASRService.GetSegments:input_type -> asr.GetSegmentsRequest
	4, // 5: asr.ASRService.SearchSegments:input_type -> asr.SearchSegmentsRequest
	6, // 6: asr.ASRService.HealthCheck:input_type -> asr.HealthCheckRequest
	1, // 7: asr.ASRService.ProcessVideo:output_type -> asr.ProcessVideoResponse
	3, // 8: asr.ASRService.GetSegments:output_type -> asr.GetSegmentsResponse
	5, // 9: asr.ASRService.SearchSegments:output_type -> asr.SearchSegmentsResponse
	7, // 10: asr.ASRService.HealthCheck:output_type -> asr.HealthCheckResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_asr_proto_init() }
func file_asr_proto_init() {
	if File_asr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asr_proto_goTypes,
		DependencyIndexes: file_asr_proto_depIdxs,
		MessageInfos:      file_asr_proto_msgTypes,
	}.Build()
	File_asr_proto = out.File
	file_asr_proto_goTypes = nil
	file_asr_proto_depIdxs = nil
}
