# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto.llm import llm_pb2 as llm_dot_llm__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llm/llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskQuestion = channel.unary_unary(
                '/llm.LLMService/AskQuestion',
                request_serializer=llm_dot_llm__pb2.QuestionRequest.SerializeToString,
                response_deserializer=llm_dot_llm__pb2.QuestionResponse.FromString,
                _registered_method=True)
        self.AskQuestionStream = channel.unary_stream(
                '/llm.LLMService/AskQuestionStream',
                request_serializer=llm_dot_llm__pb2.QuestionRequest.SerializeToString,
                response_deserializer=llm_dot_llm__pb2.TokenChunk.FromString,
                _registered_method=True)
        self.SemanticSearch = channel.unary_unary(
                '/llm.LLMService/SemanticSearch',
                request_serializer=llm_dot_llm__pb2.SearchRequest.SerializeToString,
                response_deserializer=llm_dot_llm__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GenerateEmbeddings = channel.unary_unary(
                '/llm.LLMService/GenerateEmbeddings',
                request_serializer=llm_dot_llm__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=llm_dot_llm__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.UpsertChunks = channel.unary_unary(
                '/llm.LLMService/UpsertChunks',
                request_serializer=llm_dot_llm__pb2.UpsertChunksRequest.SerializeToString,
                response_deserializer=llm_dot_llm__pb2.UpsertChunksResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AskQuestion(self, request, context):
        """MVP 第一阶段：基础问答
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskQuestionStream(self, request, context):
        """流式问答：逐 token/分片返回
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticSearch(self, request, context):
        """MVP 第一阶段：语义检索
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbeddings(self, request, context):
        """MVP 第一阶段：生成向量嵌入
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertChunks(self, request, context):
        """批量分片入库（更高吞吐）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AskQuestion,
                    request_deserializer=llm_dot_llm__pb2.QuestionRequest.FromString,
                    response_serializer=llm_dot_llm__pb2.QuestionResponse.SerializeToString,
            ),
            'AskQuestionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.AskQuestionStream,
                    request_deserializer=llm_dot_llm__pb2.QuestionRequest.FromString,
                    response_serializer=llm_dot_llm__pb2.TokenChunk.SerializeToString,
            ),
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=llm_dot_llm__pb2.SearchRequest.FromString,
                    response_serializer=llm_dot_llm__pb2.SearchResponse.SerializeToString,
            ),
            'GenerateEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbeddings,
                    request_deserializer=llm_dot_llm__pb2.EmbeddingRequest.FromString,
                    response_serializer=llm_dot_llm__pb2.EmbeddingResponse.SerializeToString,
            ),
            'UpsertChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertChunks,
                    request_deserializer=llm_dot_llm__pb2.UpsertChunksRequest.FromString,
                    response_serializer=llm_dot_llm__pb2.UpsertChunksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AskQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/AskQuestion',
            llm_dot_llm__pb2.QuestionRequest.SerializeToString,
            llm_dot_llm__pb2.QuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskQuestionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llm.LLMService/AskQuestionStream',
            llm_dot_llm__pb2.QuestionRequest.SerializeToString,
            llm_dot_llm__pb2.TokenChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/SemanticSearch',
            llm_dot_llm__pb2.SearchRequest.SerializeToString,
            llm_dot_llm__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/GenerateEmbeddings',
            llm_dot_llm__pb2.EmbeddingRequest.SerializeToString,
            llm_dot_llm__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/UpsertChunks',
            llm_dot_llm__pb2.UpsertChunksRequest.SerializeToString,
            llm_dot_llm__pb2.UpsertChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
