services:
  gateway:
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../gateway/.env
    depends_on: 
      - user-service
      - auth-service
  auth-service:
    build: 
      context: ..
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - ../services/auth-service/.env
    depends_on:
      db:
        condition: service_healthy
  user-service:
    build:
      context: ..
      dockerfile: services/user-service/Dockerfile
    ports:
      - "50052:50052"
    env_file:
      - ../services/user-service/.env
    depends_on:
      db:
        condition: service_healthy
      auth-service:
        condition: service_started
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RigelNana77
      POSTGRES_DB: arkdb
    ports:
      - "5432:5432"
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql:z
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d arkdb"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db-data: