services:
  gateway:
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../gateway/.env
    depends_on: 
      - user-service
      - auth-service
  auth-service:
    build: 
      context: ..
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - ../services/auth-service/.env
    depends_on:
      - db
  user-service:
    build:
      context: ..
      dockerfile: services/user-service/Dockerfile
    ports:
      - "50052:50052"
    env_file:
      - ../services/user-service/.env
    depends_on:
      - db
      - auth-service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RigelNana77
      POSTGRES_DB: arkdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: