services:
  gateway:
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../gateway/.env
    depends_on: 
      - user-service
      - auth-service
      - material-service
  auth-service:
    build: 
      context: ..
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - ../services/auth-service/.env
    depends_on:
      db:
        condition: service_healthy
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"


  
  user-service:
    build:
      context: ..
      dockerfile: services/user-service/Dockerfile
    ports:
      - "50052:50052"
    env_file:
      - ../services/user-service/.env
    depends_on:
      db:
        condition: service_healthy
      auth-service:
        condition: service_started
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RigelNana77
      POSTGRES_DB: arkdb
    ports:
      - "5433:5432"
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql:z
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d arkdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  material-service:
    build:
      context: ..
      dockerfile: services/material-service/Dockerfile
    ports:
      - "50053:50053"
    env_file:
      - ../services/material-service/.env
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      user-service:
        condition: service_started
      
volumes:
  db-data: