{{- $ns := .Values.namespace | default .Release.Namespace -}}

{{- if .Values.secrets }}
{{- range $name, $data := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $ns }}
  labels:
    {{- include "arkstudy.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}

{{- range $svcName, $cfg := .Values.services }}
{{- if and $cfg.enabled $cfg.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "arkstudy.fullname" $) $svcName }}
  namespace: {{ $ns }}
  labels:
    {{- include "arkstudy.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $svcName }}
stringData:
{{- range $k, $v := $cfg.secrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
{{- end }}
