// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.6
// source: proto/material/material.proto

package material

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 处理类型枚举
type ProcessingType int32

const (
	ProcessingType_OCR          ProcessingType = 0
	ProcessingType_ASR          ProcessingType = 1
	ProcessingType_LLM_ANALYSIS ProcessingType = 2
)

// Enum value maps for ProcessingType.
var (
	ProcessingType_name = map[int32]string{
		0: "OCR",
		1: "ASR",
		2: "LLM_ANALYSIS",
	}
	ProcessingType_value = map[string]int32{
		"OCR":          0,
		"ASR":          1,
		"LLM_ANALYSIS": 2,
	}
)

func (x ProcessingType) Enum() *ProcessingType {
	p := new(ProcessingType)
	*p = x
	return p
}

func (x ProcessingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_material_material_proto_enumTypes[0].Descriptor()
}

func (ProcessingType) Type() protoreflect.EnumType {
	return &file_proto_material_material_proto_enumTypes[0]
}

func (x ProcessingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingType.Descriptor instead.
func (ProcessingType) EnumDescriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{0}
}

// 处理状态枚举
type ProcessingStatus int32

const (
	ProcessingStatus_PENDING    ProcessingStatus = 0
	ProcessingStatus_PROCESSING ProcessingStatus = 1
	ProcessingStatus_COMPLETED  ProcessingStatus = 2
	ProcessingStatus_FAILED     ProcessingStatus = 3
)

// Enum value maps for ProcessingStatus.
var (
	ProcessingStatus_name = map[int32]string{
		0: "PENDING",
		1: "PROCESSING",
		2: "COMPLETED",
		3: "FAILED",
	}
	ProcessingStatus_value = map[string]int32{
		"PENDING":    0,
		"PROCESSING": 1,
		"COMPLETED":  2,
		"FAILED":     3,
	}
)

func (x ProcessingStatus) Enum() *ProcessingStatus {
	p := new(ProcessingStatus)
	*p = x
	return p
}

func (x ProcessingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_material_material_proto_enumTypes[1].Descriptor()
}

func (ProcessingStatus) Type() protoreflect.EnumType {
	return &file_proto_material_material_proto_enumTypes[1]
}

func (x ProcessingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingStatus.Descriptor instead.
func (ProcessingStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{1}
}

type MaterialInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,4,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	FileType         string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	SizeBytes        int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MaterialInfo) Reset() {
	*x = MaterialInfo{}
	mi := &file_proto_material_material_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialInfo) ProtoMessage() {}

func (x *MaterialInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialInfo.ProtoReflect.Descriptor instead.
func (*MaterialInfo) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{0}
}

func (x *MaterialInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MaterialInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MaterialInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MaterialInfo) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *MaterialInfo) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *MaterialInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MaterialInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MaterialInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UploadMaterialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadMaterialRequest_Metadata
	//	*UploadMaterialRequest_ChunkData
	Data          isUploadMaterialRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMaterialRequest) Reset() {
	*x = UploadMaterialRequest{}
	mi := &file_proto_material_material_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMaterialRequest) ProtoMessage() {}

func (x *UploadMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMaterialRequest.ProtoReflect.Descriptor instead.
func (*UploadMaterialRequest) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMaterialRequest) GetData() isUploadMaterialRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadMaterialRequest) GetMetadata() *MaterialInfo {
	if x != nil {
		if x, ok := x.Data.(*UploadMaterialRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadMaterialRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadMaterialRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadMaterialRequest_Data interface {
	isUploadMaterialRequest_Data()
}

type UploadMaterialRequest_Metadata struct {
	Metadata *MaterialInfo `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadMaterialRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadMaterialRequest_Metadata) isUploadMaterialRequest_Data() {}

func (*UploadMaterialRequest_ChunkData) isUploadMaterialRequest_Data() {}

type UploadMaterialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MaterialId    string                 `protobuf:"bytes,3,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMaterialResponse) Reset() {
	*x = UploadMaterialResponse{}
	mi := &file_proto_material_material_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMaterialResponse) ProtoMessage() {}

func (x *UploadMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMaterialResponse.ProtoReflect.Descriptor instead.
func (*UploadMaterialResponse) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{2}
}

func (x *UploadMaterialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadMaterialResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadMaterialResponse) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

type DeleteMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMaterialRequest) Reset() {
	*x = DeleteMaterialRequest{}
	mi := &file_proto_material_material_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMaterialRequest) ProtoMessage() {}

func (x *DeleteMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMaterialRequest.ProtoReflect.Descriptor instead.
func (*DeleteMaterialRequest) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteMaterialRequest) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *DeleteMaterialRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteMaterialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMaterialResponse) Reset() {
	*x = DeleteMaterialResponse{}
	mi := &file_proto_material_material_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMaterialResponse) ProtoMessage() {}

func (x *DeleteMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMaterialResponse.ProtoReflect.Descriptor instead.
func (*DeleteMaterialResponse) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMaterialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteMaterialResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListMaterialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMaterialsRequest) Reset() {
	*x = ListMaterialsRequest{}
	mi := &file_proto_material_material_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaterialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaterialsRequest) ProtoMessage() {}

func (x *ListMaterialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMaterialsRequest.ProtoReflect.Descriptor instead.
func (*ListMaterialsRequest) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{5}
}

func (x *ListMaterialsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListMaterialsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMaterialsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMaterialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Materials     []*MaterialInfo        `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMaterialsResponse) Reset() {
	*x = ListMaterialsResponse{}
	mi := &file_proto_material_material_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaterialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaterialsResponse) ProtoMessage() {}

func (x *ListMaterialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMaterialsResponse.ProtoReflect.Descriptor instead.
func (*ListMaterialsResponse) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{6}
}

func (x *ListMaterialsResponse) GetMaterials() []*MaterialInfo {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *ListMaterialsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 处理结果信息
type ProcessingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MaterialId    string                 `protobuf:"bytes,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          ProcessingType         `protobuf:"varint,4,opt,name=type,proto3,enum=material.ProcessingType" json:"type,omitempty"`
	Status        ProcessingStatus       `protobuf:"varint,5,opt,name=status,proto3,enum=material.ProcessingStatus" json:"status,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingResult) Reset() {
	*x = ProcessingResult{}
	mi := &file_proto_material_material_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingResult) ProtoMessage() {}

func (x *ProcessingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingResult.ProtoReflect.Descriptor instead.
func (*ProcessingResult) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessingResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessingResult) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *ProcessingResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProcessingResult) GetType() ProcessingType {
	if x != nil {
		return x.Type
	}
	return ProcessingType_OCR
}

func (x *ProcessingResult) GetStatus() ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return ProcessingStatus_PENDING
}

func (x *ProcessingResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ProcessingResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProcessingResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProcessingResult) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ProcessingResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 开始处理材料请求
type ProcessMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          ProcessingType         `protobuf:"varint,3,opt,name=type,proto3,enum=material.ProcessingType" json:"type,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 处理选项，如语言、模型等
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMaterialRequest) Reset() {
	*x = ProcessMaterialRequest{}
	mi := &file_proto_material_material_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMaterialRequest) ProtoMessage() {}

func (x *ProcessMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMaterialRequest.ProtoReflect.Descriptor instead.
func (*ProcessMaterialRequest) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessMaterialRequest) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *ProcessMaterialRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProcessMaterialRequest) GetType() ProcessingType {
	if x != nil {
		return x.Type
	}
	return ProcessingType_OCR
}

func (x *ProcessMaterialRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// 开始处理材料响应
type ProcessMaterialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        *ProcessingResult      `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMaterialResponse) Reset() {
	*x = ProcessMaterialResponse{}
	mi := &file_proto_material_material_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMaterialResponse) ProtoMessage() {}

func (x *ProcessMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMaterialResponse.ProtoReflect.Descriptor instead.
func (*ProcessMaterialResponse) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessMaterialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessMaterialResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessMaterialResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProcessMaterialResponse) GetResult() *ProcessingResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// 获取处理结果请求
type GetProcessingResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          ProcessingType         `protobuf:"varint,3,opt,name=type,proto3,enum=material.ProcessingType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessingResultRequest) Reset() {
	*x = GetProcessingResultRequest{}
	mi := &file_proto_material_material_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingResultRequest) ProtoMessage() {}

func (x *GetProcessingResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessingResultRequest.ProtoReflect.Descriptor instead.
func (*GetProcessingResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{10}
}

func (x *GetProcessingResultRequest) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *GetProcessingResultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProcessingResultRequest) GetType() ProcessingType {
	if x != nil {
		return x.Type
	}
	return ProcessingType_OCR
}

// 获取处理结果响应
type GetProcessingResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *ProcessingResult      `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessingResultResponse) Reset() {
	*x = GetProcessingResultResponse{}
	mi := &file_proto_material_material_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingResultResponse) ProtoMessage() {}

func (x *GetProcessingResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessingResultResponse.ProtoReflect.Descriptor instead.
func (*GetProcessingResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{11}
}

func (x *GetProcessingResultResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetProcessingResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetProcessingResultResponse) GetResult() *ProcessingResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// 列出处理结果请求
type ListProcessingResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          ProcessingType         `protobuf:"varint,3,opt,name=type,proto3,enum=material.ProcessingType" json:"type,omitempty"` // 可选，筛选特定类型
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessingResultsRequest) Reset() {
	*x = ListProcessingResultsRequest{}
	mi := &file_proto_material_material_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessingResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessingResultsRequest) ProtoMessage() {}

func (x *ListProcessingResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessingResultsRequest.ProtoReflect.Descriptor instead.
func (*ListProcessingResultsRequest) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{12}
}

func (x *ListProcessingResultsRequest) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *ListProcessingResultsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListProcessingResultsRequest) GetType() ProcessingType {
	if x != nil {
		return x.Type
	}
	return ProcessingType_OCR
}

func (x *ListProcessingResultsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProcessingResultsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 列出处理结果响应
type ListProcessingResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ProcessingResult    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessingResultsResponse) Reset() {
	*x = ListProcessingResultsResponse{}
	mi := &file_proto_material_material_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessingResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessingResultsResponse) ProtoMessage() {}

func (x *ListProcessingResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessingResultsResponse.ProtoReflect.Descriptor instead.
func (*ListProcessingResultsResponse) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{13}
}

func (x *ListProcessingResultsResponse) GetResults() []*ProcessingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListProcessingResultsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 更新处理结果请求 (供AI服务回调使用)
type UpdateProcessingResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        ProcessingStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=material.ProcessingStatus" json:"status,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProcessingResultRequest) Reset() {
	*x = UpdateProcessingResultRequest{}
	mi := &file_proto_material_material_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProcessingResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessingResultRequest) ProtoMessage() {}

func (x *UpdateProcessingResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcessingResultRequest.ProtoReflect.Descriptor instead.
func (*UpdateProcessingResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateProcessingResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateProcessingResultRequest) GetStatus() ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return ProcessingStatus_PENDING
}

func (x *UpdateProcessingResultRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateProcessingResultRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateProcessingResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 更新处理结果响应
type UpdateProcessingResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProcessingResultResponse) Reset() {
	*x = UpdateProcessingResultResponse{}
	mi := &file_proto_material_material_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProcessingResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessingResultResponse) ProtoMessage() {}

func (x *UpdateProcessingResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_material_material_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcessingResultResponse.ProtoReflect.Descriptor instead.
func (*UpdateProcessingResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_material_material_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateProcessingResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateProcessingResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_material_material_proto protoreflect.FileDescriptor

const file_proto_material_material_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/material/material.proto\x12\bmaterial\"\xed\x01\n" +
	"\fMaterialInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12+\n" +
	"\x11original_filename\x18\x04 \x01(\tR\x10originalFilename\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"v\n" +
	"\x15UploadMaterialRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.material.MaterialInfoH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"m\n" +
	"\x16UploadMaterialResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vmaterial_id\x18\x03 \x01(\tR\n" +
	"materialId\"Q\n" +
	"\x15DeleteMaterialRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"L\n" +
	"\x16DeleteMaterialResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\x14ListMaterialsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"c\n" +
	"\x15ListMaterialsResponse\x124\n" +
	"\tmaterials\x18\x01 \x03(\v2\x16.material.MaterialInfoR\tmaterials\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xbe\x03\n" +
	"\x10ProcessingResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmaterial_id\x18\x02 \x01(\tR\n" +
	"materialId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12,\n" +
	"\x04type\x18\x04 \x01(\x0e2\x18.material.ProcessingTypeR\x04type\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.material.ProcessingStatusR\x06status\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12D\n" +
	"\bmetadata\x18\a \x03(\v2(.material.ProcessingResult.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x02\n" +
	"\x16ProcessMaterialRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.material.ProcessingTypeR\x04type\x12G\n" +
	"\aoptions\x18\x04 \x03(\v2-.material.ProcessMaterialRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x17ProcessMaterialResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x122\n" +
	"\x06result\x18\x04 \x01(\v2\x1a.material.ProcessingResultR\x06result\"\x84\x01\n" +
	"\x1aGetProcessingResultRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.material.ProcessingTypeR\x04type\"\x81\x01\n" +
	"\x1bGetProcessingResultResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x06result\x18\x03 \x01(\v2\x1a.material.ProcessingResultR\x06result\"\xb7\x01\n" +
	"\x1cListProcessingResultsRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.material.ProcessingTypeR\x04type\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"k\n" +
	"\x1dListProcessingResultsResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.material.ProcessingResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xbb\x02\n" +
	"\x1dUpdateProcessingResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.material.ProcessingStatusR\x06status\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12Q\n" +
	"\bmetadata\x18\x04 \x03(\v25.material.UpdateProcessingResultRequest.MetadataEntryR\bmetadata\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x1eUpdateProcessingResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*4\n" +
	"\x0eProcessingType\x12\a\n" +
	"\x03OCR\x10\x00\x12\a\n" +
	"\x03ASR\x10\x01\x12\x10\n" +
	"\fLLM_ANALYSIS\x10\x02*J\n" +
	"\x10ProcessingStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\xa2\x05\n" +
	"\x0fMaterialService\x12U\n" +
	"\x0eUploadMaterial\x12\x1f.material.UploadMaterialRequest\x1a .material.UploadMaterialResponse(\x01\x12S\n" +
	"\x0eDeleteMaterial\x12\x1f.material.DeleteMaterialRequest\x1a .material.DeleteMaterialResponse\x12P\n" +
	"\rListMaterials\x12\x1e.material.ListMaterialsRequest\x1a\x1f.material.ListMaterialsResponse\x12V\n" +
	"\x0fProcessMaterial\x12 .material.ProcessMaterialRequest\x1a!.material.ProcessMaterialResponse\x12b\n" +
	"\x13GetProcessingResult\x12$.material.GetProcessingResultRequest\x1a%.material.GetProcessingResultResponse\x12h\n" +
	"\x15ListProcessingResults\x12&.material.ListProcessingResultsRequest\x1a'.material.ListProcessingResultsResponse\x12k\n" +
	"\x16UpdateProcessingResult\x12'.material.UpdateProcessingResultRequest\x1a(.material.UpdateProcessingResultResponseB.Z,github.com/RigelNana/arkstudy/proto/materialb\x06proto3"

var (
	file_proto_material_material_proto_rawDescOnce sync.Once
	file_proto_material_material_proto_rawDescData []byte
)

func file_proto_material_material_proto_rawDescGZIP() []byte {
	file_proto_material_material_proto_rawDescOnce.Do(func() {
		file_proto_material_material_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_material_material_proto_rawDesc), len(file_proto_material_material_proto_rawDesc)))
	})
	return file_proto_material_material_proto_rawDescData
}

var file_proto_material_material_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_material_material_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_material_material_proto_goTypes = []any{
	(ProcessingType)(0),                    // 0: material.ProcessingType
	(ProcessingStatus)(0),                  // 1: material.ProcessingStatus
	(*MaterialInfo)(nil),                   // 2: material.MaterialInfo
	(*UploadMaterialRequest)(nil),          // 3: material.UploadMaterialRequest
	(*UploadMaterialResponse)(nil),         // 4: material.UploadMaterialResponse
	(*DeleteMaterialRequest)(nil),          // 5: material.DeleteMaterialRequest
	(*DeleteMaterialResponse)(nil),         // 6: material.DeleteMaterialResponse
	(*ListMaterialsRequest)(nil),           // 7: material.ListMaterialsRequest
	(*ListMaterialsResponse)(nil),          // 8: material.ListMaterialsResponse
	(*ProcessingResult)(nil),               // 9: material.ProcessingResult
	(*ProcessMaterialRequest)(nil),         // 10: material.ProcessMaterialRequest
	(*ProcessMaterialResponse)(nil),        // 11: material.ProcessMaterialResponse
	(*GetProcessingResultRequest)(nil),     // 12: material.GetProcessingResultRequest
	(*GetProcessingResultResponse)(nil),    // 13: material.GetProcessingResultResponse
	(*ListProcessingResultsRequest)(nil),   // 14: material.ListProcessingResultsRequest
	(*ListProcessingResultsResponse)(nil),  // 15: material.ListProcessingResultsResponse
	(*UpdateProcessingResultRequest)(nil),  // 16: material.UpdateProcessingResultRequest
	(*UpdateProcessingResultResponse)(nil), // 17: material.UpdateProcessingResultResponse
	nil,                                    // 18: material.ProcessingResult.MetadataEntry
	nil,                                    // 19: material.ProcessMaterialRequest.OptionsEntry
	nil,                                    // 20: material.UpdateProcessingResultRequest.MetadataEntry
}
var file_proto_material_material_proto_depIdxs = []int32{
	2,  // 0: material.UploadMaterialRequest.metadata:type_name -> material.MaterialInfo
	2,  // 1: material.ListMaterialsResponse.materials:type_name -> material.MaterialInfo
	0,  // 2: material.ProcessingResult.type:type_name -> material.ProcessingType
	1,  // 3: material.ProcessingResult.status:type_name -> material.ProcessingStatus
	18, // 4: material.ProcessingResult.metadata:type_name -> material.ProcessingResult.MetadataEntry
	0,  // 5: material.ProcessMaterialRequest.type:type_name -> material.ProcessingType
	19, // 6: material.ProcessMaterialRequest.options:type_name -> material.ProcessMaterialRequest.OptionsEntry
	9,  // 7: material.ProcessMaterialResponse.result:type_name -> material.ProcessingResult
	0,  // 8: material.GetProcessingResultRequest.type:type_name -> material.ProcessingType
	9,  // 9: material.GetProcessingResultResponse.result:type_name -> material.ProcessingResult
	0,  // 10: material.ListProcessingResultsRequest.type:type_name -> material.ProcessingType
	9,  // 11: material.ListProcessingResultsResponse.results:type_name -> material.ProcessingResult
	1,  // 12: material.UpdateProcessingResultRequest.status:type_name -> material.ProcessingStatus
	20, // 13: material.UpdateProcessingResultRequest.metadata:type_name -> material.UpdateProcessingResultRequest.MetadataEntry
	3,  // 14: material.MaterialService.UploadMaterial:input_type -> material.UploadMaterialRequest
	5,  // 15: material.MaterialService.DeleteMaterial:input_type -> material.DeleteMaterialRequest
	7,  // 16: material.MaterialService.ListMaterials:input_type -> material.ListMaterialsRequest
	10, // 17: material.MaterialService.ProcessMaterial:input_type -> material.ProcessMaterialRequest
	12, // 18: material.MaterialService.GetProcessingResult:input_type -> material.GetProcessingResultRequest
	14, // 19: material.MaterialService.ListProcessingResults:input_type -> material.ListProcessingResultsRequest
	16, // 20: material.MaterialService.UpdateProcessingResult:input_type -> material.UpdateProcessingResultRequest
	4,  // 21: material.MaterialService.UploadMaterial:output_type -> material.UploadMaterialResponse
	6,  // 22: material.MaterialService.DeleteMaterial:output_type -> material.DeleteMaterialResponse
	8,  // 23: material.MaterialService.ListMaterials:output_type -> material.ListMaterialsResponse
	11, // 24: material.MaterialService.ProcessMaterial:output_type -> material.ProcessMaterialResponse
	13, // 25: material.MaterialService.GetProcessingResult:output_type -> material.GetProcessingResultResponse
	15, // 26: material.MaterialService.ListProcessingResults:output_type -> material.ListProcessingResultsResponse
	17, // 27: material.MaterialService.UpdateProcessingResult:output_type -> material.UpdateProcessingResultResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_material_material_proto_init() }
func file_proto_material_material_proto_init() {
	if File_proto_material_material_proto != nil {
		return
	}
	file_proto_material_material_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadMaterialRequest_Metadata)(nil),
		(*UploadMaterialRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_material_material_proto_rawDesc), len(file_proto_material_material_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_material_material_proto_goTypes,
		DependencyIndexes: file_proto_material_material_proto_depIdxs,
		EnumInfos:         file_proto_material_material_proto_enumTypes,
		MessageInfos:      file_proto_material_material_proto_msgTypes,
	}.Build()
	File_proto_material_material_proto = out.File
	file_proto_material_material_proto_goTypes = nil
	file_proto_material_material_proto_depIdxs = nil
}
