apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: arkstudy
data:
  GATEWAY_PORT: "8080"
  AUTH_GRPC_ADDR: "auth-service.arkstudy.svc.cluster.local:50051"
  USER_GRPC_ADDR: "user-service.arkstudy.svc.cluster.local:50052"
  MATERIAL_GRPC_ADDR: "material-service.arkstudy.svc.cluster.local:50053"
  LLM_GRPC_ADDR: "llm-service.arkstudy.svc.cluster.local:50054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: material-config
  namespace: arkstudy
data:
  DB_HOST: "postgres.arkstudy.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "arkdb"
  LLM_GRPC_ADDR: "llm-service.arkstudy.svc.cluster.local:50054"
  OCR_GRPC_ADDR: "ocr-service.arkstudy.svc.cluster.local:50055"
  MINIO_ENDPOINT: "minio.arkstudy.svc.cluster.local:9000"
  MINIO_BUCKET_NAME: "arkstudy"
  KAFKA_BROKERS: "kafka.arkstudy.svc.cluster.local:9092"
  KAFKA_TOPIC_OCR_REQUESTS: "ocr.requests"
  KAFKA_GROUP_ID: "material-worker"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-config
  namespace: arkstudy
data:
  DB_HOST: "postgres.arkstudy.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "arkdb"
  LLM_VECTOR_DIM: "1536"
  LLM_IVFFLAT_LISTS: "100"
  OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
  OPENAI_BASE_URL: "https://yunwu.ai/v1"
  OPENAI_MODEL: "gpt-5-chat-latest"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocr-config
  namespace: arkstudy
data:
  OCR_GRPC_ADDR: "50055"
  MINIO_ENDPOINT: "minio.arkstudy.svc.cluster.local:9000"
  MINIO_BUCKET_NAME: "arkstudy"
  PADDLE_OCR_ENDPOINT: "http://paddleocr.arkstudy.svc.cluster.local:8868/predict/ocr_system"
  # Kafka for OCR worker
  KAFKA_BROKERS: "kafka.arkstudy.svc.cluster.local:9092"
  KAFKA_TOPIC_OCR_REQUESTS: "ocr.requests"
  KAFKA_GROUP_ID: "ocr-worker"
  MATERIAL_GRPC_ADDR: "material-service.arkstudy.svc.cluster.local:50053"
