apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: arkstudy
spec:
  selector: { app: user-service }
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: arkstudy
spec:
  replicas: 1
  selector:
    matchLabels: { app: user-service }
  template:
    metadata:
      labels: { app: user-service }
    spec:
      containers:
        - name: user-service
          image: rigelnana/arkstudy-user-service:latest
          imagePullPolicy: IfNotPresent
          ports: [ { containerPort: 50052 } ]
          env:
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: db-app-secret, key: DB_USER } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: db-app-secret, key: DB_PASSWORD } }
            - name: DB_HOST
              value: postgres.arkstudy.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: arkdb
            - name: USER_GRPC_PORT
              value: "50052"
          readinessProbe:
            tcpSocket: { port: 50052 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 50052 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
